export const FIAD_CONFIG = {
  name: "Fondation Impact Afrique Durable",
  shortName: "FIAD",
  slogan: "Bâtir aujourd'hui l'Afrique de demain",
  sloganEn: "Building tomorrow's Africa today",
  email: "contact@fondation-fiad.org",
  location: "Abidjan, Côte d'Ivoire",
  founding: "2024",
  socials: {
    linkedin: "https://linkedin.com/company/fondation-fiad",
    twitter: "https://twitter.com/fondation_fiad",
    facebook: "https://facebook.com/fondationfiad",
    youtube: "https://youtube.com/@fondationfiad",
  },
};

export const NAV_ITEMS = [
  {
    label: "La Fondation",
    labelEn: "The Foundation",
    href: "/fondation",
    children: [
      { label: "Vision & Mission", labelEn: "Vision & Mission", href: "/fondation" },
      { label: "Notre Histoire", labelEn: "Our History", href: "/fondation/histoire" },
      { label: "Gouvernance", labelEn: "Governance", href: "/fondation/gouvernance" },
      { label: "Notre Équipe", labelEn: "Our Team", href: "/fondation/equipe" },
    ],
  },
  { label: "Nos Actions", labelEn: "Our Actions", href: "/nos-actions" },
  { label: "Projets", labelEn: "Projects", href: "/projets" },
  { label: "Impact", labelEn: "Impact", href: "/impact" },
  { label: "Publications", labelEn: "Publications", href: "/publications" },
  { label: "Partenaires", labelEn: "Partners", href: "/partenaires" },
  { label: "Pour les Bailleurs", labelEn: "For Donors", href: "/bailleurs", badge: "Nouveau" },
  { label: "Transparence", labelEn: "Transparency", href: "/transparence" },
  { label: "S'impliquer", labelEn: "Get Involved", href: "/impliquer" },
];

export const STRATEGIC_AXES = [
  {
    icon: "Leaf",
    title: "Développement Durable",
    titleEn: "Sustainable Development",
    description: "Promouvoir des pratiques durables pour préserver l'environnement africain.",
    descriptionEn: "Promoting sustainable practices to preserve the African environment.",
    color: "green",
  },
  {
    icon: "GraduationCap",
    title: "Éducation & Innovation",
    titleEn: "Education & Innovation",
    description: "Former les leaders de demain par l'éducation de qualité et l'innovation.",
    descriptionEn: "Training tomorrow's leaders through quality education and innovation.",
    color: "blue",
  },
  {
    icon: "Briefcase",
    title: "Entrepreneuriat",
    titleEn: "Entrepreneurship",
    description: "Accompagner les jeunes et les femmes dans la création d'entreprises.",
    descriptionEn: "Supporting youth and women in building businesses.",
    color: "gold",
  },
  {
    icon: "Users",
    title: "Inclusion Économique",
    titleEn: "Economic Inclusion",
    description: "Réduire les inégalités et favoriser l'accès aux opportunités économiques.",
    descriptionEn: "Reducing inequalities and expanding access to economic opportunities.",
    color: "purple",
  },
  {
    icon: "Globe",
    title: "Environnement & Climat",
    titleEn: "Environment & Climate",
    description: "Agir pour le climat et protéger les écosystèmes africains.",
    descriptionEn: "Taking action for climate and protecting African ecosystems.",
    color: "teal",
  },
  {
    icon: "Heart",
    title: "Impact Communautaire",
    titleEn: "Community Impact",
    description: "Renforcer les communautés locales par des initiatives à fort impact.",
    descriptionEn: "Strengthening local communities through high-impact initiatives.",
    color: "red",
  },
];

export const IMPACT_STATS = [
  { value: 500000, suffix: "+", label: "Bénéficiaires visés", labelEn: "Target beneficiaries" },
  { value: 100, suffix: "", label: "Projets planifiés", labelEn: "Planned projects" },
  { value: 15, suffix: "", label: "Pays africains", labelEn: "African countries" },
  { value: 50, suffix: "+", label: "Partenaires visés", labelEn: "Target partners" },
];

export const PROJECTS_DATA = [
  {
    id: "impact-jeunes-numeriques",
    slug: "impact-jeunes-numeriques",
    title: "Programme Impact Jeunes Numériques",
    titleEn: "Digital Youth Impact Program",
    category: "education",
    status: "active",
    location: "Abidjan, Côte d'Ivoire",
    beneficiaries: 1200,
    budget: "150 000 €",
    startDate: "2024-01",
    storyHook: "Derrière ce programme, il y a des jeunes qui refusent de subir leur avenir.",
    storyHookEn: "Behind this program are young people who refuse to let their future be decided for them.",
    storyGives: ["Des compétences", "Des outils", "Une vision"],
    storyGivesEn: ["Skills", "Tools", "A vision"],
    storyClosing: "Et surtout : une chance réelle de réussir.",
    storyClosingEn: "And above all: a real chance to succeed.",
    problem: "Les jeunes africains sont massivement sous-représentés dans l'économie numérique mondiale malgré un potentiel énorme.",
    problemEn: "African youth are massively underrepresented in the global digital economy despite enormous potential.",
    objective: "Former 1 200 jeunes aux compétences numériques et à l'entrepreneuriat tech.",
    objectiveEn: "Train 1,200 youth in digital skills and tech entrepreneurship.",
    solution: "Bootcamps intensifs, mentorat et incubation de projets numériques.",
    solutionEn: "Intensive bootcamps, mentorship and incubation of digital projects.",
    results: "850 certifiés, 120 startups créées, 340 emplois générés.",
    resultsEn: "850 certified, 120 startups created, 340 jobs generated.",
    kpis: [
      { label: "Jeunes formés", value: "1 200", icon: "Users" },
      { label: "Taux d'insertion", value: "78%", icon: "TrendingUp" },
      { label: "Startups créées", value: "120", icon: "Briefcase" },
      { label: "Emplois générés", value: "340", icon: "Award" },
    ],
    sdgs: [4, 8, 10],
    color: "green",
  },
  {
    id: "femmes-entrepreneures",
    slug: "femmes-entrepreneures",
    title: "Femmes Entrepreneures d'Afrique",
    titleEn: "Women Entrepreneurs of Africa",
    category: "entrepreneurship",
    status: "active",
    location: "Abidjan, Dakar, Accra",
    beneficiaries: 800,
    budget: "120 000 €",
    startDate: "2024-03",
    storyHook: "Derrière ce programme, il y a des femmes qui refusent que leur talent reste invisible.",
    storyHookEn: "Behind this program are women who refuse to let their talent go unseen.",
    storyGives: ["Un accompagnement sur mesure", "Un accès au financement", "Un réseau de mentores"],
    storyGivesEn: ["Tailored support", "Access to financing", "A mentor network"],
    storyClosing: "Et surtout : les moyens de transformer leur ambition en réalité.",
    storyClosingEn: "And above all: the means to turn their ambition into reality.",
    problem: "Les femmes africaines représentent 58% des travailleurs informels mais n'accèdent qu'à 7% des financements.",
    problemEn: "African women represent 58% of informal workers but access only 7% of financing.",
    objective: "Autonomiser 800 femmes entrepreneurs par l'accès aux outils, au financement et aux réseaux.",
    objectiveEn: "Empower 800 women entrepreneurs through access to tools, financing and networks.",
    solution: "Programme d'accompagnement 360° : formation, microfinancement, réseau de mentores.",
    solutionEn: "360° support program: training, microfinancing, mentor network.",
    results: "650 entreprises formalisées, 4,2M€ de chiffre d'affaires généré.",
    resultsEn: "650 businesses formalized, €4.2M in revenue generated.",
    kpis: [
      { label: "Femmes accompagnées", value: "800", icon: "Users" },
      { label: "Entreprises créées", value: "650", icon: "Briefcase" },
      { label: "CA généré", value: "4,2M€", icon: "TrendingUp" },
      { label: "Taux de survie 2 ans", value: "82%", icon: "Award" },
    ],
    sdgs: [5, 8, 10],
    color: "gold",
  },
  {
    id: "villages-verts",
    slug: "villages-verts",
    title: "Villages Verts",
    titleEn: "Green Villages",
    category: "environment",
    status: "active",
    location: "Côte d'Ivoire, Ghana, Bénin",
    beneficiaries: 5000,
    budget: "200 000 €",
    startDate: "2023-09",
    storyHook: "Derrière ce programme, il y a des communautés qui refusent de subir le changement climatique.",
    storyHookEn: "Behind this program are communities who refuse to be victims of climate change.",
    storyGives: ["Des pratiques agricoles durables", "Des ressources énergétiques propres", "Des outils adaptés à leur réalité"],
    storyGivesEn: ["Sustainable farming practices", "Clean energy resources", "Tools adapted to their reality"],
    storyClosing: "Et surtout : la capacité de protéger leur avenir, par elles-mêmes.",
    storyClosingEn: "And above all: the capacity to protect their own future.",
    problem: "La déforestation et le changement climatique menacent directement les moyens de subsistance de millions de ruraux africains.",
    problemEn: "Deforestation and climate change directly threaten the livelihoods of millions of rural Africans.",
    objective: "Transformer 20 villages en modèles d'agriculture durable et d'énergie propre.",
    objectiveEn: "Transform 20 villages into models of sustainable agriculture and clean energy.",
    solution: "Agroforesterie, panneaux solaires communautaires, formation aux pratiques durables.",
    solutionEn: "Agroforestry, community solar panels, training in sustainable practices.",
    results: "20 villages transformés, 15 000 arbres plantés, 60% de réduction des émissions locales.",
    resultsEn: "20 villages transformed, 15,000 trees planted, 60% reduction in local emissions.",
    kpis: [
      { label: "Villages transformés", value: "20", icon: "Globe" },
      { label: "Arbres plantés", value: "15 000", icon: "Leaf" },
      { label: "Bénéficiaires", value: "5 000", icon: "Users" },
      { label: "Réduction CO₂", value: "60%", icon: "TrendingUp" },
    ],
    sdgs: [13, 15, 1],
    color: "navy",
  },
];
